var G_HEIGHT_NAVBAR = 0;

var G_XNODE = G_CURRENT_DOMAIN.coordinates;
var G_IELEM = G_CURRENT_DOMAIN.elements;

var G_DISPLACEMENTS = G_CURRENT_DOMAIN.displacements;
var G_REACTIONS = G_CURRENT_DOMAIN.reactions;
var G_STRESSES = G_CURRENT_DOMAIN.stresses;
